# To enable ssh & remote debugging on app service change the base image to the one below
# FROM mcr.microsoft.com/azure-functions/python:3.0-python3.8-appservice
FROM mcr.microsoft.com/azure-functions/python:3.0-python3.8

# Install Base dependencies and utilities
RUN apt-get update && apt-get install -y --no-install-recommends \
    vim
RUN echo 'alias ll='"'"'ls $LS_OPTIONS -al'"'"'' >> ~/.bashrc 
RUN pip install --upgrade pip

ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

COPY requirements.txt /
RUN pip install -r /requirements.txt

COPY liquid_json_transform/ /home/site/wwwroot/TransformJsonToJson/
COPY template_transform.liquid.json /home/site/wwwroot/Templates/

# ENTRYPOINT [ "/bin/bash" ]
CMD [ "/azure-functions-host/Microsoft.Azure.WebJobs.Script.WebHost" ]